server:
  port: 8089

#是否开启 swagger-ui
swagger:
  enabled: true
  
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 3000MB
      max-request-size: 3000MB
      
# 文件存储路径
file:
  mac:
    path: ~/file/
    modelPath: /Users/calvin/AIAS/2_training_platform/platform-train/models/resnet50_dl4j_inference.v3.zip
    dataRootPath: /Users/calvin/AIAS/2_training_platform/platform-train/data/ #压缩包解压缩文件夹
    savePath: /Users/calvin/AIAS/2_training_platform/platform-train/models/NewResNet50.zip #模型训练好后存放的路径
  linux:
    path: /home/aias/file/
    modelPath: /home/aias/file/resnet50_dl4j_inference.v3.zip
    dataRootPath: /home/aias/file/image_root/ #压缩包解压缩文件夹
    savePath: /home/aias/file//model/ #模型训练好后存放的文件夹
  windows:
    path: C:\\aias\\file\\
    modelPath: C:\\aias\\file\\resnet50_dl4j_inference.v3.zip
    dataRootPath: C:\\aias\\file\\image_root\\ #压缩包解压缩文件夹
    savePath: C:\\aias\\file\\modelv2\\ #模型训练好后存放的文件夹
  # 文件大小 /M
  maxSize: 3000
