# Server Port
server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8
  baseUri: http://127.0.0.1:${server.port}

# 参数配置
config:
  # 输出文字最大长度
  maxLength: 128

model:
  # 设备类型 cpu gpu
  device: cpu
  # 如果是 CPU 推理，最高设置为 CPU 核心数 (Core Number)
  poolSize: 4
  # ocr 文字识别
  ocrv4:
    # server detection model URI
    det: D:\\ai_projects\\AIAS\\3_api_platform\\api-platform\\models\\ocr\\ch_PP-OCRv4_det_infer.zip
    # server recognition model URI
    rec: D:\\ai_projects\\AIAS\\3_api_platform\\api-platform\\models\\ocr\\ch_PP-OCRv4_rec_infer.zip

  # 图片转正
  mlsd:
    # mlsd model URI
    model: D:\\ai_projects\\AIAS\\3_api_platform\\api-platform\\models\\ocr\\mlsd_traced_model_onnx.zip

  # whisper 语音识别，模型三个 tiny 231M, base 397M, small 1.13G
  asr:
    type: base
    # 静音检测模型
    vad: D:\\ai_projects\\AIAS\\3_api_platform\\api-platform\\models\\asr\\silero_vad.onnx
    # tiny 模型
    tiny: D:\\ai_projects\\AIAS\\3_api_platform\\api-platform\\models\\asr\\traced_whisper_tiny.pt
    # base 模型
    base: D:\\ai_projects\\AIAS\\3_api_platform\\api-platform\\models\\asr\\traced_whisper_base.pt
    # small 模型
    small: D:\\ai_projects\\AIAS\\3_api_platform\\api-platform\\models\\asr\\traced_whisper_small.pt

  # 模型路径,注意路径最后要有分隔符
  translation:
    modelPath: D:\\ai_projects\\AIAS\\3_api_platform\\api-platform\\models\\trans\\
    # 模型名字
    modelName: traced_translation_cpu.pt

  # 图像高清
  sr:
    # 模型路径
    modelPath: D:\\ai_projects\\AIAS\\3_api_platform\\api-platform\\models\\sr\\
    # 人脸检测模型
    faceModelName: retinaface_traced_model.pt
    # 人像分割模型
    faceSegModelName: parsenet_traced_model.pt
    # 人脸修复模型
    faceGanModelName: gfpgan_traced_model.pt
    # 图像超分模型
    srModelName: realsr_traced_model.pt

  seg:
    # 遮罩层
    mask: false
    # 模型路径
    modelPath: D:\\ai_projects\\AIAS\\3_api_platform\\api-platform\\models\\seg\\
    # 通用分割模型
    bigModelName: u2net.onnx
    middleModelName: silueta.onnx
    smallModelName: u2netp.onnx
    # 人体分割模型
    humanModelName: human.onnx
    # 动漫分割模型
    animeModelName: anime.onnx
    # 衣服分割模型
    clothModelName: cloth.onnx

  # 黑白照片山色
  color:
    modelPath: D:\\ai_projects\\AIAS\\3_api_platform\\api-platform\\models\\color\\
    # 模型名字
    modelName: traced_ddcolor_cpu.pt

  # 图片预处理工具箱
  preprocess:
    dptDepthModelPath: D:\\ai_projects\\AIAS\\3_api_platform\\api-platform\\models\\controlnet\\dpt_depth.pt
    midasDepthModelPath: D:\\ai_projects\\AIAS\\3_api_platform\\api-platform\\models\\controlnet\\midas_depth.pt
    bodyModelPath: D:\\ai_projects\\AIAS\\3_api_platform\\api-platform\\models\\controlnet\\body.pt
    faceModelPath: D:\\ai_projects\\AIAS\\3_api_platform\\api-platform\\models\\controlnet\\face.pt
    handModelPath: D:\\ai_projects\\AIAS\\3_api_platform\\api-platform\\models\\controlnet\\hand.pt
    hedModelPath: D:\\ai_projects\\AIAS\\3_api_platform\\api-platform\\models\\controlnet\\hed.pt
    pidiCpuModelPath: D:\\ai_projects\\AIAS\\3_api_platform\\api-platform\\models\\controlnet\\pidi_cpu.pt
    pidiGpuModelPath: D:\\ai_projects\\AIAS\\3_api_platform\\api-platform\\models\\controlnet\\pidi_gpu.pt
    lineartModelPath: D:\\ai_projects\\AIAS\\3_api_platform\\api-platform\\models\\controlnet\\lineart.pt
    lineartAnimeModelPath: D:\\ai_projects\\AIAS\\3_api_platform\\api-platform\\models\\controlnet\\lineart_anime.pt
    lineartCoarseModelPath: D:\\ai_projects\\AIAS\\3_api_platform\\api-platform\\models\\controlnet\\lineart_coarse.pt
    mlsdModelPath: D:\\ai_projects\\AIAS\\3_api_platform\\api-platform\\models\\controlnet\\mlsd.pt
    normalbaeModelPath: D:\\ai_projects\\AIAS\\3_api_platform\\api-platform\\models\\controlnet\\normalbae.pt
    upernetModelPath: D:\\ai_projects\\AIAS\\3_api_platform\\api-platform\\models\\controlnet\\upernet.pt